question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Sports",
        "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]
    },
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "Which modern country is known as &quot;The Graveyard of Empires&quot;?",
     "correct_answer": "Afghanistan",
     "incorrect_answers": ["China", "Iraq", "Russia"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Danganronpa: Trigger Happy Havoc, what is the protagonist&#039;s name?",
     "correct_answer": "Makoto Naegi",
     "incorrect_answers": ["Hajime Hinata", "Nagito Komaeda",
                           "Komaru Naegi"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Science: Computers",
     "question": "Which of these is the name for the failed key escrow device introduced by the National Security Agency in 1993?",
     "correct_answer": "Clipper Chip",
     "incorrect_answers": ["Enigma Machine", "Skipjack", "Nautilus"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Science: Computers",
     "question": "The Harvard architecture for micro-controllers added which additional bus?",
     "correct_answer": "Instruction",
     "incorrect_answers": ["Address", "Data", "Control"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In &quot;A Certain Scientific Railgun&quot;, how many &quot;sisters&quot; did Accelerator have to kill to achieve the rumored level 6?",
     "correct_answer": "20,000",
     "incorrect_answers": ["128", "10,000", "5,000"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What is the official national language of Pakistan?",
     "correct_answer": "Urdu",
     "incorrect_answers": ["Indian", "Punjabi", "Pashto"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "What is the colour of unoxidized blood?",
     "correct_answer": "Red",
     "incorrect_answers": ["Blue", "Purple", "Green"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Science: Computers",
     "question": "When was the programming language &quot;C#&quot; released?",
     "correct_answer": "2000",
     "incorrect_answers": ["1998", "1999", "2001"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "What is the first Studio Album to be released on the Internet with a &quot;Pay-What-You-Want&quot; price?",
     "correct_answer": "In Rainbows",
     "incorrect_answers": ["The Help Album",
                           "Skrillex and Diplo Present Jack &Uuml;",
                           "Blackstar"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "What is the name the location-based augmented reality game developed by Niantic before Pok&eacute;mon GO?",
     "correct_answer": "Ingress",
     "incorrect_answers": ["Aggress", "Regress", "Digress"]},
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "What is the historical name of Sri Lanka?",
     "correct_answer": "Ceylon",
     "incorrect_answers": ["Myanmar", "Colombo", "Badulla"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "How old was Lyndon B. Johnson when he assumed the role of President of the United States?",
     "correct_answer": "55", "incorrect_answers": ["50", "60", "54"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "&quot;All the Boys&quot; by Panic! At the Disco was released as a bonus track on what album?",
     "correct_answer": "Too Weird To Live, Too Rare To Die!",
     "incorrect_answers": ["A Fever You Can&#039;t Sweat Out",
                           "Death Of A Bachelor", "Vices &amp; Virtues"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "Which of these is not an Ed Sheeran album?",
     "correct_answer": "-", "incorrect_answers": ["+", "X", "&divide;"]},
    {"type": "multiple", "difficulty": "medium", "category": "Art",
     "question": "Which of these are the name of a famous marker brand?",
     "correct_answer": "Copic",
     "incorrect_answers": ["Dopix", "Cofix", "Marx"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "What is Pikachu&#039;s National Pok&eacute;Dex Number?",
     "correct_answer": "#025",
     "incorrect_answers": ["#001", "#031", "#109"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Pokemon Red &amp; Blue, what is the name of HM05?",
     "correct_answer": "Flash",
     "incorrect_answers": ["Strength", "Cut", "Fly"]},
    {"type": "multiple", "difficulty": "hard", "category": "Geography",
     "question": "What is the county seat of King County, Washington?",
     "correct_answer": "Seattle",
     "incorrect_answers": ["Bellevue", "Enumclaw", "Skykomish"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Who directed the movies &quot;Pulp Fiction&quot;, &quot;Reservoir Dogs&quot; and &quot;Django Unchained&quot;?",
     "correct_answer": "Quentin Tarantino",
     "incorrect_answers": ["Martin Scorcese", "Steven Spielberg",
                           "James Cameron"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The French word to travel is &quot;Travail&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Science &amp; Nature",
     "question": "What is the largest animal currently on Earth?",
     "correct_answer": "Blue Whale",
     "incorrect_answers": ["Orca", "Colossal Squid", "Giraffe"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Which puzzle game was designed by a Russian programmer, featuring Russian buildings and music?",
     "correct_answer": "Tetris",
     "incorrect_answers": ["Jenga", "Boulder Dash", "Puzzled"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Which of the following was not developed by Bethesda?",
     "correct_answer": "Fallout: New Vegas",
     "incorrect_answers": ["Fallout 3", "The Elder Scrolls V: Skyrim",
                           "Fallout 4"]},
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "What is the smallest country in the world?",
     "correct_answer": "Vatican City",
     "incorrect_answers": ["Maldives", "Monaco", "Malta"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Comics",
     "question": "What is the name of the comic about a young boy, and a tiger who is actually a stuffed animal?",
     "correct_answer": "Calvin and Hobbes",
     "incorrect_answers": ["Winnie the Pooh", "Albert and Pogo",
                           "Peanuts"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Which of these is not a DLC vehicle in &quot;Mario Kart 8&quot;?",
     "correct_answer": "Wild Wiggler",
     "incorrect_answers": ["Bone Rattler", "B Dasher", "300 SL Roadster"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "Which country does the electronic music duo &quot;The Knife&quot; originate from?",
     "correct_answer": "Sweden",
     "incorrect_answers": ["Finland", "Denmark", "Norway"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "From where does the Nintendo video game character Mario derive his name?",
     "correct_answer": "The landlord of the American headquarters",
     "incorrect_answers": ["Shigeru Miyamoto&#039;s father in law",
                           "Satoru Iwata&#039;s plumber",
                           "The date (Mar 10) that Donkey Kong was released."]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "What is the main character&#039;s name in &quot;Braid&quot;?",
     "correct_answer": "Tim",
     "incorrect_answers": ["Boregard", "James", "Jackson"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Television",
     "question": "In 2008, British celebrity chef Gordon Ramsay believes he almost died after suffering what accident in Iceland while filming?",
     "correct_answer": "Slipping off a cliff, and nearly drowning in icy water",
     "incorrect_answers": [
         "Crash landing when arriving at Keflav&iacute;k airport",
         "A minor car accident in a snowstorm",
         "Being served under-cooked chicken at his hotel"]},
    {"type": "multiple", "difficulty": "hard", "category": "Geography",
     "question": "What is the most populous Muslim-majority nation in 2010?",
     "correct_answer": "Indonesia",
     "incorrect_answers": ["Saudi Arabia", "Iran", "Sudan"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Comics",
     "question": "What is the designation given to the Marvel Cinematic Universe?",
     "correct_answer": "Earth-199999",
     "incorrect_answers": ["Earth-616", "Earth-10005", "Earth-2008"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science: Mathematics",
     "question": "A universal set, or a set that contains all sets, exists.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "What is the name of the ship which was only a few miles away from the RMS Titanic when it struck an iceberg on April 14, 1912?",
     "correct_answer": "Californian",
     "incorrect_answers": ["Carpathia", "Cristol", "Commerce"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What is the fifth largest country by area?",
     "correct_answer": "Brazil",
     "incorrect_answers": ["United States", "Australia", "India"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Music",
     "question": "Which of these artists did NOT feature in the fitfh studio album &quot;Humanz&quot; by British virtual band Gorillaz?",
     "correct_answer": "Snoop Dogg",
     "incorrect_answers": ["Vince Staples", "Pusha T", "Danny Brown"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "The first Maxis game to feature the fictional language &quot;Simlish&quot; was The Sims (2000).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "hard", "category": "Geography",
     "question": "What is the area of Vatican City?",
     "correct_answer": "0.44km^2",
     "incorrect_answers": ["0.10km^2", "0.86km^2", "12.00km^2"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "hard", "category": "History",
     "question": "How many women joined the United States Armed Services during World War II?",
     "correct_answer": "350,000",
     "incorrect_answers": ["225,000", "100,000", "500,000"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "Who crowned Charlemagne as Holy Roman Emperor on Christmas Day in 800?",
     "correct_answer": "Pope Leo III",
     "incorrect_answers": ["Pope Urban IV", "Pope Stephen V",
                           "Pope Valentine"]},
    {"type": "multiple", "difficulty": "medium", "category": "Vehicles",
     "question": "Which of the following vehicles featured a full glass roof at base model?",
     "correct_answer": "Renault Avantime",
     "incorrect_answers": ["Chevy Volt", "Mercedes-Benz A-Class",
                           "Honda Odyssey"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Cartoon &amp; Animations",
     "question": "In &quot;SpongeBob SquarePants&quot;, what is the name of Sandy Cheek&#039;s place of residence?",
     "correct_answer": "Sandy&#039;s Treedome",
     "incorrect_answers": ["&quot;The Dome&quot;", "Sandy&#039;s Bubble",
                           "Auquatic Reseach Centre"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "Which chemical element has the lowest boiling point?",
     "correct_answer": "Helium",
     "incorrect_answers": ["Hydrogen", "Neon", "Nitrogen"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Satella in &quot;Re:Zero&quot; is the witch of what?",
     "correct_answer": "Envy",
     "incorrect_answers": ["Pride", "Sloth", "Wrath"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Film",
     "question": "Which documentary film maker wrote and starred in the film &quot;My Scientology Movie&quot; which first debuted in 2015?",
     "correct_answer": "Louis Theroux",
     "incorrect_answers": ["Errol Morris", "Joe Berlinger",
                           "Adam Curtis"]}]
